Version control line

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,14 +1,23 @@
 # This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
 # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
 
-name: Java CI with Maven
+name: CI Build
 
 on:
-  push:
-  pull_request:
+  pull_request_target:
+    branches:
+      - main
     types:
       - closed
-    branches: [ "main" ]
+  pull_request:
+    branches:
+      - main
+  workflow_dispatch:
+    inputs:
+      force_snapshot_release:
+        description: 'Update the snapshot release on github'
+        required: false
+        type: boolean
 
 jobs:
   build:
@@ -24,26 +33,87 @@ jobs:
         distribution: 'temurin'
         cache: maven
 
+
+    - name: Check if a snapshot release should be made and set environment variable
+      run: echo "MAKE_SNAPSHOT_RELEASE=${{ inputs.force_snapshot_release || (github.event.pull_request.base.ref == 'main' && github.event.action == 'closed' && github.event.pull_request.merged == true) }}" >> $GITHUB_ENV
+
       # configure git
     - name: setup git config
       run: |
         git config user.name ${{ github.actor }}
         git config user.email "<>"
 
+    - name: Fetch branches (unless PR was merged)
+      if: ${{ env.MAKE_SNAPSHOT_RELEASE == 'false' }}
+      run: |
+        # as we aren't building main, let's fetch it
+        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
+        if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
+          # Fetch from contributor’s fork
+          git remote add fork ${{ github.event.pull_request.head.repo.clone_url }}
+          git fetch fork ${{ github.event.pull_request.head.ref }}:${{ github.head_ref }}
+        else
+          # Fetch from the same repo
+          git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}
+        fi
+
+    - name: Fail if src/main has changes but CHANGELOG.md does not (unless PR was merged)
+      if: ${{ env.MAKE_SNAPSHOT_RELEASE == 'false' }}
+      run: |
+        set -e
+        CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }})
+        if echo "$CHANGED_FILES" | grep -q '^src/main' && ! echo "$CHANGED_FILES" | grep -q '^CHANGELOG.md$'; then
+          echo "Directory src/main changed without an update of CHANGELOG.md, this is not allowed. Please update CHANGELOG.md"
+          exit 1
+        fi
+
+      # Read version changelog before anything else - if there is a formatting error
+      # in the changelog (which happens), we fail fast
+      # Do this even if we will not make the snapshot release, so the changelog is checked as part of a normal
+      # ci run.
+
+    - name: Check Changelog formatting
+      id: get-changelog
+      uses: superfaceai/release-changelog-action@v1
+      with:
+        path-to-changelog: CHANGELOG.md
+        version: ${{ inputs.release_version }}
+        operation: read
+
     - name: Build with Maven
       run: mvn -Pzip install
 
-    - name: change tag 'snapshot' to current commit
-      if: ${{ github.event.pull_request.base.ref == 'main' && github.event.action == 'closed' && github.event.pull_request.merged == true}} # only make snapshot release if it is a push to main
-      run: |
-            git tag -f snapshot
-            git push -f origin --tags
+    # delete the snapshot release (the release action does not update the
+    # body, so we have to delete the whole thing)
+    - name: Delete Snapshot Release
+      if: ${{ env.MAKE_SNAPSHOT_RELEASE == 'true' }}
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: gh release delete snapshot --cleanup-tag --yes || echo "Error deleting snapshot release - continuing anyway"
 
+    - name: change tag 'snapshot' to current commit
+      if: ${{ env.MAKE_SNAPSHOT_RELEASE == 'true' }}
+      run: |
+        git tag -f snapshot
+        git push -f origin --tags
+
+    - name: Make Release Body
+      if: ${{ env.MAKE_SNAPSHOT_RELEASE  == 'true' }}
+      run: |
+        cat src/build/snapshot-release/release-body-header.md > target/release-body.md
+        echo "# Changes" >> target/release-body.md
+        cat <<'EOF' >> target/release-body.md 
+        ${{ steps.get-changelog.outputs.changelog }}
+        EOF
+        cat src/build/snapshot-release/release-body-footer.md >> target/release-body.md        
+
+    # Make github release
     - name: Release
       uses: softprops/action-gh-release@v2
-      if: ${{ github.event.pull_request.base.ref == 'main' && github.event.action == 'closed' && github.event.pull_request.merged == true}} # only make snapshot release if it is a push to main
+      if: ${{ env.MAKE_SNAPSHOT_RELEASE  == 'true' }}
       with:
         name: Latest snapshot release
         tag_name: snapshot
-        body_path: src/build/release/release-body.md
+        body_path: target/release-body.md
         files: target/qudt-public-repo-*.zip
+        prerelease: true
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -120,14 +120,6 @@ jobs:
         env:
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      # Make github release
-      - name: Release
-        uses: softprops/action-gh-release@v2
-        with:
-          tag_name: v${{ inputs.release_version }}
-          body_path: src/build/release/release-body.md
-          files: target/checkout/target/qudt-public-repo-*.zip
-
       # Read version changelog
       - id: get-changelog
         name: Get version changelog
@@ -136,6 +128,22 @@ jobs:
           path-to-changelog: CHANGELOG.md
           version: ${{ inputs.release_version }}
           operation: read
+
+      # Make github release
+      - name: Make Release Body
+        run: |
+          cat src/build/release/release-body-header.md > target/release-body.md
+          echo "# Changes" >> target/release-body.md 
+          cat <<'EOF' >> target/release-body.md 
+          ${{ steps.get-changelog.outputs.changelog }}
+          EOF
+          cat src/build/release/release-body-footer.md >> target/release-body.md
+      - name: Release
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: v${{ inputs.release_version }}
+          body_path: target/release-body.md
+          files: target/checkout/target/qudt-public-repo-*.zip
 
       # create the pull request
       - name: Create Pull Request
@@ -161,6 +169,12 @@ jobs:
             # Next Steps
             
             Please rebase this PR on top of `main` after verifying the release is ok. 
+
+      # delete the snapshot release (so we do not accumulate snapshots of all versions over time)
+      - name: Delete Snapshot Release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: gh release delete snapshot --cleanup-tag --yes || echo "Error deleting snapshot release - continuing anyway"
 
       # print the summary
       - name: Print summary
