Make github actions more resilient
With this commit, trying to delete the snapshot release when that release does not exist will not fail.

Also, the format check of CHANGELOG.md is executed in each CI build.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -172,7 +172,7 @@ jobs:
       - name: Delete Snapshot Release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: gh release delete snapshot --cleanup-tag --yes
+        run: gh release delete snapshot --cleanup-tag --yes || echo "Error deleting snapshot release - continuing anyway"
 
       # print the summary
       - name: Print summary
